### ISSUE TITLE
rhel7 - setting timezone again and again

### ISSUE THREAD

**Issue by bby-bishopclark** [Stromweld/timezone_iii#6]
The time zone on RHEL7/Centos7 is continually set, with every chef run:

test.box.work Recipe: timezone_iii::default
test.box.work   * yum_package[tzdata] action install (up to date)
test.box.work Recipe: timezone_iii::rhel7
test.box.work   * execute[timedatectl --no-ask-password set-timezone America/Vancouver] action run
test.box.work     - execute timedatectl --no-ask-password set-timezone America/Vancouver
test.box.work   * template[/etc/sysconfig/clock] action create (up to date)
test.box.work   * execute[tzdata-update] action nothing (skipped due to action :nothing)

It maybe could have tougher guard code, unless I'm doing something obviously wrong.

**Comment by Stromweld** [comment]
it shouldn't hurt anything, but i agree a better solution would to add a not_if option and check to see if timezone is already correctly set.

**Comment by Stromweld** [comment]
Borgified's PR fixed this issue.

**Comment by borgified** [comment]
can you please push it to chef supermarket, ty

**Comment by Stromweld** [comment]
Just pushed. Thanks for the reminder.
