### ISSUE TITLE
UTC=true should be set in Amazon Linux

### ISSUE THREAD

**Issue by limitusus** [Stromweld/timezone_iii#9]
Amazon Linux discourages editing `UTC=true` line in `/etc/sysconfig/clock` as its hardware clock is set UTC.

> Do not change the UTC=true entry to another value. This entry is for the hardware clock, and does not need to be adjusted when you're setting a different time zone on your instance.

For now https://github.com/Stromweld/timezone_iii/blob/master/templates/default/rhel/clock.erb only writes `ZONE` but `UTC` line is encouraged to be configurable.

**Comment by Stromweld** [comment]
I believe the linux kernel defaults to UTC=true if the setting is missing. So it should maintain the same behavior. However it may be better idea in the template to add that config option with an attribute to default set it to true and users can change the attribute if they aren't running their servers hwclock set to UTC.

**Comment by limitusus** [comment]
I agree with you.
I made a PR for that.

**Comment by Stromweld** [comment]
Thanks for the PR. It has been merged.
